name: main
on:
  push:
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build all & assembly Docker images
        run: chmod +x gradlew && ./gradlew build
