name: main
on:
  push:
    branches:
      - 'master'
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build & test all
        run: chmod +x gradlew && ./gradlew build docker --info
      - name: Build & publish docker images for app
        run: ./gradlew dockerPush --info
      - name: Publish API library to Maven packages
        env:
          USER: ${{ secrets.PACKAGES_USER }}
          TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: ./gradlew api:publish
